### ISSUE TITLE
Please add these Dell and Ruckus devices

### ISSUE THREAD

**Issue by marcelrc** [glpi-project/sysobject.ids#1]
674.10895.3030 Dell NETWORKING PowerConnect 5524
674.10895.3036 Dell NETWORKING PowerConnect 7024P
25053.3.1.4.100 Ruckus NETWORKING R610
25053.3.1.4.103 Ruckus NETWORKING T310c

**Comment by g-bougard** [comment]
Hi @marcelrc 
sorry for the very long delay.
Thank you for your contribution.
