### ISSUE TITLE
Please add ISCOM switch 2648G

### ISSUE THREAD

**Issue by supriadi817** [glpi-project/sysobject.ids#11]
Hi,
I have some ISCOM switch, but it seems isn't in glpi-agent database sysobject.ids. Here is it the output of my ISCOM switch.

![image](https://user-images.githubusercontent.com/112539221/218026949-47d9ac5b-e695-4f5a-a28b-043e6714560d.png)

Thanks.

**Comment by g-bougard** [comment]
Hi @supriadi817 
thank you for your contribution.
I also found some other ISCOM devices sysObjectID I added too.
