### ISSUE TITLE
Add Mellanox MSN2700

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/sysobject.ids#15]
```
# snmpget -v2c -c public 10.100.237.101 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.33049.1.1.1.2700
```
[msn2700.txt](https://github.com/glpi-project/sysobject.ids/files/11061651/msn2700.txt)

**Comment by g-bougard** [comment]
Hi @GuidoWilden 
in your run, the agent found a partial match and was able to set the model to `MSN2700-CS2F` and the type to `NETWORKING`. Is this correct ? If yes, adding the entry won't change anything in the inventory of your device, this will just change the debug log.

**Comment by GuidoWilden** [comment]
Hi @g-bougard
Yes this is correct however the model does not get aded to the database. I thought the discovery task would add the model or am I missing something here?

**Comment by g-bougard** [comment]
The database is there to first set the device type. Then it can be used to set the model is necessary, but this is not absolutely required as the agent can retrieve it from a ANMP OID.

**Comment by g-bougard** [comment]
The database is there to first set the device type. Then it can be used to set the model is necessary, but this is not absolutely required as the agent can retrieve it from a ANMP OID.

**Comment by g-bougard** [comment]
The database is there to first set the device type. Then it can be used to set the model is necessary, but this is not absolutely required as the agent can retrieve it from a ANMP OID.

**Comment by g-bougard** [comment]
The database is there to first set the device type. Then it can be used to set the model is necessary, but this is not absolutely required as the agent can retrieve it from a SNMP OID.

**Comment by g-bougard** [comment]
The database is there to first set the device type. Then it can be used to set the model is necessary, but this is not absolutely required as the agent can retrieve it from a SNMP OID.
