### ISSUE TITLE
Please, add MikroTik Switch CRS326-24G-2S+RM

### ISSUE THREAD

**Issue by tabad** [glpi-project/sysobject.ids#17]
I include below information regarding [MikroTik Switch CRS326-24G-2S+RM](https://mikrotik.com/product/CRS326-24G-2SplusRM).

````bash
$ snmpget -v2c -c public "w.x.y.z" 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.14988.1
````

````bash
# glpi-netinventory --credentials version:2c,community:public --debug --host "w.x.y.z" > mikrotik_crsS326-24g-2s+rm.txt
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] Current run expiration timeout: 1.0 hour
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: w.x.y.z
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.14988.1 in database
[debug] [thread 1] #1, sysobjectID match: mikrotik mib support enabled
[debug] [thread 1] termination
[debug] All netinventory threads terminated
````

> **Note 1**: The content of file [`mikrotik_crsS326-24g-2s+rm.txt`](https://github.com/glpi-project/sysobject.ids/files/11152376/mikrotik_crsS326-24g-2s%2Brm.txt) has been anonymized.
> **Note 2**: You can find information about RouterOS SNMP and RouterOS MIB [here](https://help.mikrotik.com/docs/display/ROS/SNMP)
> **Note 3**: The Management Information Base (MIB) for RouterOS v7 can be downloaded from [here](https://download.mikrotik.com/routeros/7.8/mikrotik.mib).
> **Note 4**: The Management Information Base (MIB) for RouterOS v6 can be downloaded from [here](https://download.mikrotik.com/routeros/6.48.6/mikrotik.mib).

I'd like you to consider this device.

Best regards.

**Comment by g-bougard** [comment]
Hello @tabad 
same question than in #16, I don't see any issue.
