### ISSUE TITLE
Please Add FS Switch 

### ISSUE THREAD

**Issue by KingObal** [glpi-project/sysobject.ids#27]
hello, 

I don't know if it's the right place and the right way do it, Feel free to direct me to a more suitable location for my request.

I'd like to inventory FS switches but i can't get much information on them. I had to enable the mac import and update rules.

1. S3400-48T4SP
2. S3400-24T4FP
3. S3900-24T4S-R
4. S3150-8T2FP

I've added the OIDs to my sysobject.ids file with a tab between : 

52642.1.437.0	FS	NETWORKING	S3150-8T2FP
52642.1.439.0	FS	NETWORKING	S3400-24T4FP
52642.1.445.0	FS	NETWORKING	S3400-48T4SP
52642.1.446.0	FS	NETWORKING	S3900-24T4S-R

I also have an snmpwalk for those switches than i can send by mail.
I can send you the modified sysobject.ids file too.

Best regards and thank you for your help.

**Comment by g-bougard** [comment]
Hi @KingObal 

okay, I'll add your entries to the sysobject.ids file.

If you have a [snmpwalk output in the right format](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output), you can send me to me at: `gbougard <at> teclib <dot> com`
I'll check it to see if I can even improve FS inventory. If you have a private MIB, this can also help, and tell me in the mail what serialnumber is expected.
