### ISSUE TITLE
Discover and invotory for Meraki MR36

### ISSUE THREAD

**Issue by XpineauGG** [glpi-project/sysobject.ids#28]
Hi,

I would like to invotory Meraki MR36 but i cannot find it in sysobject.ids, someone can help me ?

Regards

**Comment by g-bougard** [comment]
Hi @XpineauGG 

have you checked [sysobject.ids contribution section](https://github.com/glpi-project/sysobject.ids?tab=readme-ov-file#contribution) ?

You can also check the [snmp device ids database](https://glpi-agent.readthedocs.io/en/latest/database.html#snmp-device-ids-database) documentation.

**Comment by g-bougard** [comment]
Closing without user feedback.
