### ISSUE TITLE
Add Dell N3048EP-ON network switch

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/sysobject.ids#29]
Related to [16942](https://github.com/glpi-project/glpi/issues/16942): `snmpwalk` attached.
[snmpwalk.txt.zip](https://github.com/glpi-project/sysobject.ids/files/15020695/snmpwalk.txt.zip)

```
snmpget -v2c -c private 10.120.20.10 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.674.10895.3084
```

```
glpi-netdiscovery --credentials version:2c,community:private --debug --host 10.120.20.10
[debug] initializing job 1
[debug] initializing block 10.120.20.10-10.120.20.10
[debug] Current netdiscovery run expiration timeout: few minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 1 worker
[debug] #1, scanning 10.120.20.10
[debug] #1, partial match for sysobjectID .1.3.6.1.4.1.674.10895.3084 on manufacturer ID
[debug] #1, - scanning 10.120.20.10 with SNMP, credentials 1: success
[debug] #1, - scanning 10.120.20.10 with netbios: no result
[debug] #1, - scanning 10.120.20.10 with echo ping: success
[debug] #1, - scanning 10.120.20.10 in arp table: no result
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DESCRIPTION>Dell EMC Networking N3048EP-ON, 6.7.1.47, Linux 4.14.174, v1.0.5</DESCRIPTION>
      <DNSHOSTNAME>10.120.20.10</DNSHOSTNAME>
      <FIRMWARE>6.7.1.47</FIRMWARE>
      <IP>10.120.20.10</IP>
      <MAC>20:04:0f:02:28:d9</MAC>
      <MANUFACTURER>Dell</MANUFACTURER>
      <MODEL>N3048EP-ON</MODEL>
      <SERIAL>CN0JDFTFDND0084E0086</SERIAL>
      <SNMPHOSTNAME>ldnaz-aswb01</SNMPHOSTNAME>
      <UPTIME>190 days, 19:25:35.02</UPTIME>
    </DEVICE>
    <MODULEVERSION>6.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
```

Please let me know if there is anything else required.

**Comment by GuidoWilden** [comment]
Here the output of `snmpwalk -v 2c -c private -t 15 -Cc -On -Ox 10.120.20.10 .1`
[snmpwalk02.txt.zip](https://github.com/glpi-project/sysobject.ids/files/15021388/snmpwalk02.txt.zip)

**Comment by g-bougard** [comment]
Hi @GuidoWilden 

also there was a problem with Dell as we could not set the type for this manufacturer as they produces printers & networking devices.

I also updated glpi-agent to support partial match on sysobjectID part in [this commit](https://github.com/glpi-project/glpi-agent/commit/f2b70982d253be054a2d68e0cefd8d438e57dc68) so the problem should not happen for other Dell devices if you use at least the next nightly build.

**Comment by GuidoWilden** [comment]
Thank you @g-bougard, all working now.

**Comment by g-bougard** [comment]
Hi @GuidoWilden 

FYI, I also added a dedicated Dell MibSupport module to help support Dell devices which are not specified in sysObject.ids file. It is included in latest nightly build.

**Comment by GuidoWilden** [comment]
Rereading your previous post: these are the only two switches running OS/firmware 10.5.3.3. Maybe worth updating. We have more switches on v10 but they are running 10.5.4.0 and these came in perfectly fine.
