### ISSUE TITLE
MIB intelbras

### ISSUE THREAD

**Issue by EdnardoMaximiliano** [glpi-project/sysobject.ids#31]
[MIB.zip](https://github.com/glpi-project/sysobject.ids/files/15168182/MIB.zip)

**Comment by g-bougard** [comment]
Hi @EdnardoMaximiliano 

please provide a [snmpwalk output of your device in the expected fortmat](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output).

**Comment by g-bougard** [comment]
Closing without user feedback. Also https://github.com/glpi-project/glpi-agent/issues/769 should still answer the requirement and [current glpi-agent nightly build](https://nightly.glpi-project.org/glpi-agent/) should handle Intelbras devices.

@EdnardoMaximiliano Next glpi-agent version should provide the required support. If you test [current glpi-agent nightly build](https://nightly.glpi-project.org/glpi-agent/) and found your specific device model is not supported, please open a [glpi-agent issue](https://github.com/glpi-project/glpi-agent/issues).
