### ISSUE TITLE
Discovery and inventory of Aerohive devices

### ISSUE THREAD

**Issue by djanjusevic-srce** [glpi-project/sysobject.ids#37]
Hello!

We have few Aerohive devices of type NETWORKING we would like to get inventoried:

AP250 (Aerohive HiveOS 10.3r3 build-260166)
AP305C (Aerohive HiveOS 10.3r5 build-265338 )
AP410C (Aerohive HiveOS 10.2r0 build-252452)
AP1130 (Aerohive HiveOS 10.3r3 build-260166)

Command 

`snmpget -v2c -c xyzabc "serverIP" 1.3.6.1.2.1.1.2.0 `

returns the same

`SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.26928.1`

for all 4 devices. Zipped inventories are attached. 
[Aerohive.zip](https://github.com/user-attachments/files/17475720/Aerohive.zip)

Thank you in advance!

Kind Regards,
djanjusevic

**Comment by g-bougard** [comment]
Hi @djanjusevic-srce 

Aerohive support has been added to current glpi-agent nightly builds: https://nightly.glpi-project.org/glpi-agent/

Can you test it and tell if your devices are supported as expected ?

**Comment by djanjusevic-srce** [comment]
Hi @g-bougard 

Tested and it works flawlessly - thank you!

I will now close this issue. 

Kind Regards,
djanjusevic
